// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package veriff.actions;

import org.apache.commons.lang3.builder.ToStringBuilder;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

import veriff.proxies.Document;
import veriff.proxies.Person;
import veriff.proxies.Verification;

public class Java_CreateSession_ToString extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __createSession;
	private veriff.proxies.CreateSession createSession;

	public Java_CreateSession_ToString(IContext context, IMendixObject createSession)
	{
		super(context);
		this.__createSession = createSession;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.createSession = this.__createSession == null ? null : veriff.proxies.CreateSession.initialize(getContext(), __createSession);

		// BEGIN USER CODE
		if (createSession == null) {
			return null;
		}
		Verification verification = createSession.getVerification_CreateSession();
		if (verification == null) {
			return null;
		}
		ToStringBuilder toStringBuilder = new ToStringBuilder(createSession);
		Person person = verification.getPerson_Verification();
		if (person == null) {
			toStringBuilder.append("person", "empty");
		} else {
			toStringBuilder.append("person", person);
		}
		Document document = verification.getDocument_Verification();
		if (document == null) {
			toStringBuilder.append("document", "empty");
		} else {
			toStringBuilder.append("document", document);
		}
		
		return toStringBuilder
				.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_CreateSession_ToString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
