// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package veriff.actions;

import org.apache.commons.lang3.builder.ToStringBuilder;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import veriff.proxies.Verification_Response;

public class Java_CreateSession_Response_ToString extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __createSession;
	private veriff.proxies.CreateSession_Response createSession;

	public Java_CreateSession_Response_ToString(IContext context, IMendixObject createSession)
	{
		super(context);
		this.__createSession = createSession;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.createSession = this.__createSession == null ? null : veriff.proxies.CreateSession_Response.initialize(getContext(), __createSession);

		// BEGIN USER CODE
		if (createSession == null) {
			return null;
		}
		ToStringBuilder toStringBuilder = new ToStringBuilder(createSession);
		Verification_Response verification = createSession.getVerification_Response_CreateSession_Response();
		if (verification == null) {
			toStringBuilder.append("verification", "empty");
		} else {
			toStringBuilder.append("verification", toString(verification));
		}
		return toStringBuilder.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_CreateSession_Response_ToString";
	}

	// BEGIN EXTRA CODE
	private static String toString(Verification_Response verification) throws CoreException {
		ToStringBuilder toStringBuilder = new ToStringBuilder(verification);
		toStringBuilder.append("id", verification.get_id());
		toStringBuilder.append("baseUrl", verification.getBaseUrl());
		toStringBuilder.append("sessionToken", verification.getSessionToken());
		toStringBuilder.append("url", verification.getUrl());
		return toStringBuilder.toString();
	}
	// END EXTRA CODE
}
